### ISSUE TITLE
What to disable/enable in Plex?

### ISSUE THREAD

**Issue by DankMemeGuy** [plexstreams/plex-auto-scan#2]
I noticed Movies is updating fine, but TV isn't. Are these settings in Plex supposed to be enabled or disabled?

Server 'library' settings:
- Scan my library automatically
- Run a partial scan when changes are detected
- Scan my library periodically

I'm not sure what would cause TV to not be updated but Movies is always up-to-date.

Any help is appreciated/!!

**Comment by plexstreams** [comment]
With Google Drive the idea is to minimize the number of scans because of API bans etc. I would set periodic scans to one day if you are allowed to do full scans.

Check the log for errors. There is no difference in scanning Movies vs. TV Shows. It all boils down to scanning a path on the file system. Also make sure that your TV Shows library in Plex is pointing to the correct path on the file system and that your Google Drive is mount and working.

**Comment by DankMemeGuy** [comment]
I went through all the settings and I could not figure out what was wrong for the life of me. So I went searching for plex and turns out my sorting was wrong. I had been sorting TV shows by "last added" but I should have sorted by "last episode date added" I realized the script is working perfectly.

Sorry for wasting your time! Thank you for the help :)
